# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Converter(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 246)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.coinsInput = QtWidgets.QLineEdit(self.centralwidget)
        self.coinsInput.setGeometry(QtCore.QRect(200, 40, 121, 31))
        self.coinsInput.setObjectName("coinsInput")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 40, 211, 31))
        self.label_2.setObjectName("label_2")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(250, 80, 71, 31))
        self.convertButton.setObjectName("convertButton")
        self.coinsBox = QtWidgets.QComboBox(self.centralwidget)
        self.coinsBox.setGeometry(QtCore.QRect(330, 40, 121, 31))
        self.coinsBox.setObjectName("coinsBox")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.coinsBox.addItem("")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 80, 131, 31))
        self.label_3.setObjectName("label_3")
        self.couinsValueLabel = QtWidgets.QLabel(self.centralwidget)
        self.couinsValueLabel.setGeometry(QtCore.QRect(90, 130, 311, 41))
        self.couinsValueLabel.setText("")
        self.couinsValueLabel.setObjectName("couinsValueLabel")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 140, 51, 16))
        self.label_4.setObjectName("label_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 10, 47, 13))
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 0, 281, 41))
        self.label_5.setObjectName("label_5")
        self.coinsBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.coinsBox_2.setGeometry(QtCore.QRect(120, 80, 121, 31))
        self.coinsBox_2.setObjectName("coinsBox_2")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        self.coinsBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Enter the amount of your coins :"))
        self.convertButton.setText(_translate("MainWindow", "Convert"))
        self.coinsBox.setItemText(0, _translate("MainWindow", "Dollar"))
        self.coinsBox.setItemText(1, _translate("MainWindow", "SyrianPound"))
        self.coinsBox.setItemText(2, _translate("MainWindow", "Euro"))
        self.coinsBox.setItemText(3, _translate("MainWindow", "SaudiRial"))
        self.coinsBox.setItemText(4, _translate("MainWindow", "KuwaitDinar"))
        self.coinsBox.setItemText(5, _translate("MainWindow", "UAEDirham"))
        self.coinsBox.setItemText(6, _translate("MainWindow", "JordanDinar"))
        self.label_3.setText(_translate("MainWindow", "Convert to ..."))
        self.label_4.setText(_translate("MainWindow", "Value :"))
        self.label.setText(_translate("MainWindow", "\n"
"Convert your currency"))
        self.label_5.setText(_translate("MainWindow", "Convert your currency"))
        self.coinsBox_2.setItemText(0, _translate("MainWindow", "Dollar"))
        self.coinsBox_2.setItemText(1, _translate("MainWindow", "Euro"))
        self.coinsBox_2.setItemText(2, _translate("MainWindow", "SaudiRial"))
        self.coinsBox_2.setItemText(3, _translate("MainWindow", "KuwaitDinar"))
        self.coinsBox_2.setItemText(4, _translate("MainWindow", "UAEDirham"))
        self.coinsBox_2.setItemText(5, _translate("MainWindow", "JordanDinar"))
        self.coinsBox_2.setItemText(6, _translate("MainWindow", "SyrianPound"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Converter()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
